MAINTAINER Alessandro Rossi <al.rossi87@gmail.com>
FROM YOUR_REPOSITORY_URL/kubealex/rhel-image-mode-demo:soe
RUN dnf install -y java-17-openjdk.x86_64 mariadb-server
RUN systemctl enable mariadb
RUN rm /usr/bin/java && ln -s /usr/lib/jvm/jre-17-openjdk/bin/java /usr/bin/java
COPY files/*.jar /opt/spring-petclinic.jar
COPY files/petclinic.service /usr/lib/systemd/system/petclinic.service
RUN systemctl enable petclinic
